# Generated by Django 6.1.1 on 2026-09-05 04:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchiveOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=32)),
                ("rows_processed", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("error_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.CharField(db_index=True, max_length=255)),
                ("actor_role", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"],
                        name="idx_audit_target_time",
                    ),
                    models.Index(fields=["actor_id", "-created_at"], name="idx_audit_actor_time"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=255),
                ),
                ("requested_by", models.CharField(default="anonymous", max_length=255)),
                ("module_slug", models.CharField(db_index=True, max_length=100)),
                ("action", models.CharField(blank=True, max_length=100, null=True)),
                ("request_json", models.JSONField(default=dict)),
                ("normalized_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancel_requested", "Cancel Requested"),
                            ("cancelled", "Cancelled"),
                            ("timed_out", "Timed Out"),
                            ("dead_letter", "Dead Letter"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=5)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                (
                    "progress_stage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("progress_message", models.TextField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error_json", models.JSONField(blank=True, null=True)),
                (
                    "webhook_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "webhook_secret_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("webhook_attempts", models.PositiveIntegerField(default=0)),
                (
                    "lease_owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_webhook_retrieved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("result_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="idx_jobs_status_created"),
                    models.Index(fields=["module_slug", "status"], name="idx_jobs_mod_status"),
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="idx_jobs_tenant_created",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("priority__gte", 0), ("priority__lte", 9)),
                        name="jobs_priority_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("progress_percent__gte", 0), ("progress_percent__lte", 100)
                        ),
                        name="jobs_progress_percent_range",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("tenant_id", "idempotency_key"),
                        name="uniq_jobs_tenant_idempotency",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobResultArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.UUIDField(db_index=True, unique=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("module_slug", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=32)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error_json", models.JSONField(blank=True, null=True)),
                ("source_finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_webhook_retrieved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("archive_reason", models.CharField(max_length=255)),
                ("archive_metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-archived_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "module_slug"],
                        name="idx_archive_tenant_mod",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("worker", "Worker"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="flow_auditor.job",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["job", "created_at"], name="idx_job_events_job_time")
                ],
            },
        ),
    ]
