"""Unified service, protocol, and port definitions and resolution utilities."""

from __future__ import annotations

# Cisco ASA keyword -> port mappings
PORT_MAP: dict[str, int] = {
    "ftp-data": 20,
    "ftp": 21,
    "ssh": 22,
    "telnet": 23,
    "smtp": 25,
    "time": 37,
    "nameserver": 42,
    "whois": 43,
    "tacacs": 49,
    "dns": 53,
    "domain": 53,
    "bootps": 67,
    "bootpc": 68,
    "tftp": 69,
    "gopher": 70,
    "finger": 79,
    "http": 80,
    "www": 80,
    "pop2": 109,
    "pop3": 110,
    "sunrpc": 111,
    "ident": 113,
    "nntp": 119,
    "ntp": 123,
    "netbios-ns": 137,
    "netbios-dgm": 138,
    "netbios-ssn": 139,
    "imap4": 143,
    "snmp": 161,
    "snmp-trap": 162,
    "xdmcp": 177,
    "bgp": 179,
    "irc": 194,
    "dnsix": 195,
    "mobile-ip": 434,
    "pim-auto-rp": 496,
    "https": 443,
    "h323": 1720,
    "ldap": 389,
    "kerberos": 88,
    "klogin": 543,
    "kshell": 544,
    "pptp": 1723,
    "l2tp": 1701,
    "rdp": 3389,
    "mssql": 1433,
    "mysql": 3306,
    "oracle": 1521,
    "radius": 1812,
    "radius-acct": 1813,
    "sip": 5060,
    "rtsp": 554,
    "syslog": 514,
    "lpd": 515,
    "exec": 512,
    "login": 513,
    "rsh": 514,
    "talk": 517,
    "rip": 520,
    "uucp": 540,
}

# ICMP types
ICMP_TYPES: dict[str, int] = {
    "echo-reply": 0,
    "unreachable": 3,
    "source-quench": 4,
    "redirect": 5,
    "alternate-address": 6,
    "echo": 8,
    "router-advertisement": 9,
    "router-solicitation": 10,
    "time-exceeded": 11,
    "parameter-problem": 12,
    "timestamp": 13,
    "timestamp-reply": 14,
    "information-request": 15,
    "information-reply": 16,
    "mask-request": 17,
    "mask-reply": 18,
    "traceroute": 30,
    "conversion-error": 31,
    "mobile-redirect": 32,
}

# Protocol numbers
PROTO_NUMS: dict[str, int] = {
    "icmp": 1,
    "igmp": 2,
    "tcp": 6,
    "udp": 17,
    "gre": 47,
    "esp": 50,
    "ah": 51,
    "eigrp": 88,
    "ospf": 89,
    "pim": 103,
    "vrrp": 112,
}

# Juniper Junos application mappings
JUNOS_APPS: dict[str, list[str]] = {
    "junos-aol": ["tcp/5190"],
    "junos-bgp": ["tcp/179"],
    "junos-biff": ["udp/512"],
    "junos-bootpc": ["udp/68"],
    "junos-bootps": ["udp/67"],
    "junos-chargen": ["tcp/19", "udp/19"],
    "junos-cifs": ["tcp/445"],
    "junos-cvspserver": ["tcp/2401"],
    "junos-dhcp-relay": ["udp/67"],
    "junos-discard": ["tcp/9", "udp/9"],
    "junos-dns-tcp": ["tcp/53"],
    "junos-dns-udp": ["udp/53"],
    "junos-echo": ["tcp/7", "udp/7"],
    "junos-finger": ["tcp/79"],
    "junos-ftp": ["tcp/21"],
    "junos-ftp-data": ["tcp/20"],
    "junos-gnutella": ["tcp/6346", "udp/6346"],
    "junos-gopher": ["tcp/70"],
    "junos-gprs-gtp-c": ["udp/2123"],
    "junos-gprs-gtp-u": ["udp/2152"],
    "junos-gprs-gtp-v0": ["udp/3386"],
    "junos-gprs-sctp": ["ip/132"],
    "junos-gre": ["ip/47"],
    "junos-h323": ["tcp/1720"],
    "junos-http": ["tcp/80"],
    "junos-http-ext": ["tcp/8080"],
    "junos-https": ["tcp/443"],
    "junos-icmp-all": ["icmp/any"],
    "junos-icmp-ping": ["icmp/8"],
    "junos-icmp6-all": ["icmp/any"],
    "junos-icmp6-dst-unreach": ["icmp/1"],
    "junos-icmp6-echo-reply": ["icmp/129"],
    "junos-icmp6-echo-request": ["icmp/128"],
    "junos-icmp6-router-adv": ["icmp/134"],
    "junos-icmp6-router-sol": ["icmp/133"],
    "junos-icmp6-time-exceed": ["icmp/3"],
    "junos-ident": ["tcp/113"],
    "junos-ike": ["udp/500"],
    "junos-imap": ["tcp/143"],
    "junos-imaps": ["tcp/993"],
    "junos-internet-locator-service": ["tcp/389"],
    "junos-irc": ["tcp/6667"],
    "junos-l2tp": ["udp/1701"],
    "junos-ldap": ["tcp/389"],
    "junos-lpr": ["tcp/515"],
    "junos-mail": ["tcp/25"],
    "junos-mgcp-ca": ["udp/2727"],
    "junos-mgcp-ua": ["udp/2427"],
    "junos-ms-rpc": ["tcp/135"],
    "junos-ms-rpc-any": ["tcp/135"],
    "junos-ms-rpc-epm": ["tcp/135"],
    "junos-ms-rpc-iis": ["tcp/1025"],
    "junos-ms-rpc-tcp": ["tcp/135"],
    "junos-ms-rpc-udp": ["udp/135"],
    "junos-ms-sql": ["tcp/1433"],
    "junos-msn": ["tcp/1863"],
    "junos-nbds": ["udp/138"],
    "junos-nbname": ["udp/137"],
    "junos-netbios-dgm": ["udp/138"],
    "junos-netbios-ns": ["udp/137"],
    "junos-netbios-session": ["tcp/139"],
    "junos-netbios-ssn": ["tcp/139"],
    "junos-nfs": ["tcp/2049", "udp/2049"],
    "junos-nfsd-tcp": ["tcp/2049"],
    "junos-nfsd-udp": ["udp/2049"],
    "junos-nntp": ["tcp/119"],
    "junos-ntp": ["udp/123"],
    "junos-ospf": ["ip/89"],
    "junos-pc-anywhere": ["tcp/5631", "udp/5632"],
    "junos-persistent-nat": ["any/any"],
    "junos-ping": ["icmp/8"],
    "junos-pingv6": ["icmp/128"],
    "junos-pop3": ["tcp/110"],
    "junos-pptp": ["tcp/1723"],
    "junos-printer": ["tcp/515"],
    "junos-r2h": ["tcp/21"],
    "junos-radacct": ["udp/1813"],
    "junos-radius": ["udp/1812"],
    "junos-rdate": ["tcp/37"],
    "junos-rdp": ["tcp/3389"],
    "junos-realaudio": ["tcp/7070", "udp/6970"],
    "junos-rip": ["udp/520"],
    "junos-ripng": ["udp/521"],
    "junos-rlogin": ["tcp/513"],
    "junos-rmon": ["udp/162"],
    "junos-rmon-trap": ["udp/162"],
    "junos-rsh": ["tcp/514"],
    "junos-rtsp": ["tcp/554"],
    "junos-samba": ["tcp/139", "tcp/445", "udp/137", "udp/138"],
    "junos-sftp": ["tcp/22"],
    "junos-sip": ["tcp/5060", "udp/5060"],
    "junos-smb": ["tcp/445"],
    "junos-smb-session": ["tcp/139"],
    "junos-smtp": ["tcp/25"],
    "junos-smtps": ["tcp/465"],
    "junos-snmp": ["udp/161"],
    "junos-snmp-agentx": ["tcp/705"],
    "junos-snmptrap": ["udp/162"],
    "junos-sql-monitor": ["udp/1434"],
    "junos-sqlsrv": ["tcp/1433"],
    "junos-ssh": ["tcp/22"],
    "junos-sun-rpc": ["tcp/111", "udp/111"],
    "junos-sun-rpc-any": ["tcp/111", "udp/111"],
    "junos-sun-rpc-mountd-tcp": ["tcp/111"],
    "junos-sun-rpc-mountd-udp": ["udp/111"],
    "junos-sun-rpc-nfs-tcp": ["tcp/2049"],
    "junos-sun-rpc-nfs-udp": ["udp/2049"],
    "junos-sun-rpc-portmapping-tcp": ["tcp/111"],
    "junos-sun-rpc-portmapping-udp": ["udp/111"],
    "junos-sun-rpc-rquotad-tcp": ["tcp/111"],
    "junos-sun-rpc-rquotad-udp": ["udp/111"],
    "junos-sun-rpc-tcp": ["tcp/111"],
    "junos-sun-rpc-udp": ["udp/111"],
    "junos-syslog": ["udp/514"],
    "junos-tacacs": ["tcp/49", "udp/49"],
    "junos-tacacs-ds": ["tcp/65"],
    "junos-talk": ["udp/517"],
    "junos-tcp-any": ["tcp/any"],
    "junos-telnet": ["tcp/23"],
    "junos-tftp": ["udp/69"],
    "junos-traceroute": ["udp/33434"],
    "junos-udp-any": ["udp/any"],
    "junos-uucp": ["tcp/540"],
    "junos-vnc": ["tcp/5900"],
    "junos-wais": ["tcp/210"],
    "junos-who": ["udp/513"],
    "junos-whois": ["tcp/43"],
    "junos-x-windows": ["tcp/6000"],
    "junos-xdmcp": ["udp/177"],
    "junos-xdmcp-tcp": ["tcp/177"],
    "junos-xdmcp-udp": ["udp/177"],
    "junos-yppasswdd": ["udp/111"],
    "any": ["any/any"],
}

# Comprehensive built-in named-service -> {proto, port} map (from FlowApprovalChecker)
BUILTIN_SERVICE_MAP: dict[str, dict[str, str | int]] = {
    # Cisco ASA TCP keywords
    "aol": {"proto": "tcp", "port": 5190},
    "bgp": {"proto": "tcp", "port": 179},
    "chargen": {"proto": "tcp", "port": 19},
    "cifs": {"proto": "tcp", "port": 3020},
    "citrix-ica": {"proto": "tcp", "port": 1494},
    "cmd": {"proto": "tcp", "port": 514},
    "ctiqbe": {"proto": "tcp", "port": 2748},
    "daytime": {"proto": "tcp", "port": 13},
    "discard": {"proto": "tcp", "port": 9},
    "domain": {"proto": "tcp", "port": 53},
    "echo": {"proto": "tcp", "port": 7},
    "exec": {"proto": "tcp", "port": 512},
    "finger": {"proto": "tcp", "port": 79},
    "ftp": {"proto": "tcp", "port": 21},
    "ftp-data": {"proto": "tcp", "port": 20},
    "gopher": {"proto": "tcp", "port": 70},
    "h323": {"proto": "tcp", "port": 1720},
    "hostname": {"proto": "tcp", "port": 101},
    "http": {"proto": "tcp", "port": 80},
    "https": {"proto": "tcp", "port": 443},
    "ident": {"proto": "tcp", "port": 113},
    "imap4": {"proto": "tcp", "port": 143},
    "irc": {"proto": "tcp", "port": 194},
    "kerberos": {"proto": "tcp", "port": 88},
    "klogin": {"proto": "tcp", "port": 543},
    "kshell": {"proto": "tcp", "port": 544},
    "ldap": {"proto": "tcp", "port": 389},
    "ldaps": {"proto": "tcp", "port": 636},
    "login": {"proto": "tcp", "port": 513},
    "lotusnotes": {"proto": "tcp", "port": 1352},
    "lpd": {"proto": "tcp", "port": 515},
    "netbios-ssn": {"proto": "tcp", "port": 139},
    "nfs": {"proto": "tcp", "port": 2049},
    "nntp": {"proto": "tcp", "port": 119},
    "pcanywhere-data": {"proto": "tcp", "port": 5631},
    "pim-auto-rp": {"proto": "tcp", "port": 496},
    "pop2": {"proto": "tcp", "port": 109},
    "pop3": {"proto": "tcp", "port": 110},
    "pptp": {"proto": "tcp", "port": 1723},
    "rsh": {"proto": "tcp", "port": 514},
    "rtsp": {"proto": "tcp", "port": 554},
    "sip": {"proto": "tcp", "port": 5060},
    "smtp": {"proto": "tcp", "port": 25},
    "sqlnet": {"proto": "tcp", "port": 1522},
    "ssh": {"proto": "tcp", "port": 22},
    "sunrpc": {"proto": "tcp", "port": 111},
    "tacacs": {"proto": "tcp", "port": 49},
    "talk": {"proto": "tcp", "port": 517},
    "telnet": {"proto": "tcp", "port": 23},
    "uucp": {"proto": "tcp", "port": 540},
    "whois": {"proto": "tcp", "port": 43},
    "www": {"proto": "tcp", "port": 80},
    # Cisco ASA UDP keywords
    "biff": {"proto": "udp", "port": 512},
    "bootpc": {"proto": "udp", "port": 68},
    "bootps": {"proto": "udp", "port": 67},
    "dhcp": {"proto": "udp", "port": 67},
    "dnsix": {"proto": "udp", "port": 195},
    "domain-udp": {"proto": "udp", "port": 53},
    "isakmp": {"proto": "udp", "port": 500},
    "mobile-ip": {"proto": "udp", "port": 434},
    "nameserver": {"proto": "udp", "port": 42},
    "netbios-dgm": {"proto": "udp", "port": 138},
    "netbios-ns": {"proto": "udp", "port": 137},
    "ntp": {"proto": "udp", "port": 123},
    "radius": {"proto": "udp", "port": 1645},
    "radius-acct": {"proto": "udp", "port": 1646},
    "rip": {"proto": "udp", "port": 520},
    "secureid-udp": {"proto": "udp", "port": 5510},
    "sip-udp": {"proto": "udp", "port": 5060},
    "snmp": {"proto": "udp", "port": 161},
    "snmptrap": {"proto": "udp", "port": 162},
    "syslog": {"proto": "udp", "port": 514},
    "tacacs-udp": {"proto": "udp", "port": 49},
    "tftp": {"proto": "udp", "port": 69},
    "time": {"proto": "udp", "port": 37},
    "who": {"proto": "udp", "port": 513},
    "xdmcp": {"proto": "udp", "port": 177},
    # Junos predefined
    "junos-ftp": {"proto": "tcp", "port": 21},
    "junos-ftp-data": {"proto": "tcp", "port": 20},
    "junos-tftp": {"proto": "udp", "port": 69},
    "junos-http": {"proto": "tcp", "port": 80},
    "junos-https": {"proto": "tcp", "port": 443},
    "junos-smtp": {"proto": "tcp", "port": 25},
    "junos-smtps": {"proto": "tcp", "port": 465},
    "junos-pop3": {"proto": "tcp", "port": 110},
    "junos-pop3s": {"proto": "tcp", "port": 995},
    "junos-imap": {"proto": "tcp", "port": 143},
    "junos-imaps": {"proto": "tcp", "port": 993},
    "junos-ssh": {"proto": "tcp", "port": 22},
    "junos-telnet": {"proto": "tcp", "port": 23},
    "junos-dns-tcp": {"proto": "tcp", "port": 53},
    "junos-dns-udp": {"proto": "udp", "port": 53},
    "junos-ldap": {"proto": "tcp", "port": 389},
    "junos-ldaps": {"proto": "tcp", "port": 636},
    "junos-ntp": {"proto": "udp", "port": 123},
    "junos-snmp-agentx": {"proto": "tcp", "port": 705},
    "junos-snmp": {"proto": "udp", "port": 161},
    "junos-snmptrap": {"proto": "udp", "port": 162},
    "junos-syslog": {"proto": "udp", "port": 514},
    "junos-bgp": {"proto": "tcp", "port": 179},
    "junos-ldp-tcp": {"proto": "tcp", "port": 646},
    "junos-ldp-udp": {"proto": "udp", "port": 646},
    "junos-msdp": {"proto": "tcp", "port": 639},
    "junos-rip": {"proto": "udp", "port": 520},
    "junos-pptp": {"proto": "tcp", "port": 1723},
    "junos-rtsp": {"proto": "tcp", "port": 554},
    "junos-sip": {"proto": "tcp", "port": 5060},
    "junos-sip-udp": {"proto": "udp", "port": 5060},
    "junos-h323": {"proto": "tcp", "port": 1720},
    "junos-nntp": {"proto": "tcp", "port": 119},
    "junos-finger": {"proto": "tcp", "port": 79},
    "junos-whois": {"proto": "tcp", "port": 43},
    "junos-irc": {"proto": "tcp", "port": 194},
    "junos-tacacs": {"proto": "tcp", "port": 49},
    "junos-tacacs-ds": {"proto": "tcp", "port": 65},
    "junos-radius": {"proto": "udp", "port": 1812},
    "junos-radacct": {"proto": "udp", "port": 1813},
    "junos-sunrpc-tcp": {"proto": "tcp", "port": 111},
    "junos-sunrpc-udp": {"proto": "udp", "port": 111},
    "junos-nfsd-tcp": {"proto": "tcp", "port": 2049},
    "junos-nfsd-udp": {"proto": "udp", "port": 2049},
    "junos-netbios-dgm": {"proto": "udp", "port": 138},
    "junos-netbios-ns": {"proto": "udp", "port": 137},
    "junos-netbios-ssn": {"proto": "tcp", "port": 139},
    "junos-smb": {"proto": "tcp", "port": 445},
    "junos-ms-sql": {"proto": "tcp", "port": 1433},
    "junos-mysql": {"proto": "tcp", "port": 3306},
    "junos-rdp": {"proto": "tcp", "port": 3389},
    "junos-twamp": {"proto": "tcp", "port": 862},
    # Common aliases
    "imap": {"proto": "tcp", "port": 143},
    "dns": {"proto": "udp", "port": 53},
    "imaps": {"proto": "tcp", "port": 993},
    "smtps": {"proto": "tcp", "port": 465},
    "pop3s": {"proto": "tcp", "port": 995},
    "smb": {"proto": "tcp", "port": 445},
    "rdp": {"proto": "tcp", "port": 3389},
    "mysql": {"proto": "tcp", "port": 3306},
    "mssql": {"proto": "tcp", "port": 1433},
}


def resolve_port(token: str | None) -> str | None:
    """Resolve a port token (number or ASA port keyword) to a port string."""
    if not token:
        return None
    token_str = str(token).strip()
    if token_str.isdigit():
        return token_str
    mapped = PORT_MAP.get(token_str.lower())
    if mapped is not None:
        return str(mapped)
    return token_str


def parse_service(
    service_str: str, service_overrides: dict[str, dict] | None = None
) -> list[dict[str, str | int]]:
    """Parse a service string into normalized [{proto, port_or_range}]."""
    raw = service_str.strip().lower()
    if not raw or raw in ("any", "any/any"):
        return [{"proto": "any", "port": "any"}]

    if service_overrides and raw in service_overrides:
        val = service_overrides[raw]
        return [val] if isinstance(val, dict) else val

    if "/" in raw:
        proto, port_part = raw.split("/", 1)
        if port_part.isdigit():
            return [{"proto": proto, "port": int(port_part)}]
        # Check if port_part is range "80-85"
        if "-" in port_part:
            p1, p2 = port_part.split("-", 1)
            if p1.isdigit() and p2.isdigit():
                return [
                    {"proto": proto, "start_port": int(p1), "end_port": int(p2), "port": port_part}
                ]
        return [{"proto": proto, "port": port_part}]

    if raw in BUILTIN_SERVICE_MAP:
        entry = BUILTIN_SERVICE_MAP[raw]
        return [{"proto": str(entry["proto"]), "port": entry["port"]}]

    if raw.isdigit():
        return [{"proto": "any", "port": int(raw)}]

    return [{"proto": "any", "port": raw}]
